# Generated by Django 3.1.3 on 2020-12-30 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_registro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_registro', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=200)),
                ('patente', models.CharField(max_length=6)),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField()),
                ('tipo', models.CharField(max_length=1000)),
                ('motivo', models.CharField(max_length=1000)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.sede')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
