# Generated by Django 3.1.3 on 2020-12-30 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('Rut', models.CharField(max_length=200)),
                ('Sede', models.CharField(choices=[('Casa central', 'Casa central'), ('Campus macul', 'Campus macul'), ('Campus providencia', 'Campus providencia')], default='Casa central', max_length=100)),
                ('Incio_Turno', models.DateTimeField(auto_now_add=True)),
                ('Fin_Turno', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Porteromacul',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('Rut', models.CharField(max_length=200)),
                ('Sede', models.CharField(choices=[('Casa central', 'Casa central'), ('Campus macul', 'Campus macul'), ('Campus providencia', 'Campus providencia')], default='Campus macul', max_length=100)),
                ('Incio_Turno', models.DateTimeField(auto_now_add=True)),
                ('Fin_Turno', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Porteroprovidencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('Rut', models.CharField(max_length=200)),
                ('Sede', models.CharField(choices=[('Casa central', 'Casa central'), ('Campus macul', 'Campus macul'), ('Campus providencia', 'Campus providencia')], default='Campus providencia', max_length=100)),
                ('Incio_Turno', models.DateTimeField(auto_now_add=True)),
                ('Fin_Turno', models.DateField()),
            ],
        ),
    ]
