# Generated by Django 3.1.3 on 2021-01-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('rut', models.CharField(max_length=200)),
                ('sede', models.CharField(max_length=200)),
                ('incio_Turno', models.DateTimeField(auto_now_add=True)),
                ('fin_Turno', models.DateField()),
            ],
        ),
    ]
