# Generated by Django 3.1.3 on 2020-12-28 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SedeCentro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Sede', models.CharField(choices=[('Casa central', 'Casa central'), ('Campus macul', 'Campus macul'), ('Campus providencia', 'Campus providencia')], default='Casa central', max_length=100)),
                ('Tipousuario', models.CharField(max_length=100)),
                ('Cantidad_estacionamientos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SedeMacul',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Sede', models.CharField(choices=[('Casa central', 'Casa central'), ('Campus macul', 'Campus macul'), ('Campus providencia', 'Campus providencia')], default='Campus macul', max_length=100)),
                ('Tipousuario', models.CharField(max_length=100)),
                ('Cantidad_estacionamientos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SedeProvidencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Sede', models.CharField(choices=[('Casa central', 'Casa central'), ('Campus macul', 'Campus macul'), ('Campus providencia', 'Campus providencia')], default='Campus providencia', max_length=100)),
                ('Tipousuario', models.CharField(max_length=100)),
                ('Cantidad_estacionamientos', models.IntegerField()),
            ],
        ),
    ]
