# Generated by Django 3.1.3 on 2021-01-05 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registro', '0001_initial'),
        ('Reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_estacionamiento', models.CharField(max_length=10)),
                ('ocupado', models.BooleanField(default=True)),
                ('registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro.registro')),
                ('reserva', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Reservas.reserva')),
            ],
        ),
    ]
