# Generated by Django 3.1.3 on 2020-12-30 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('campus_macul', models.CharField(max_length=100)),
                ('campus_providencia', models.CharField(max_length=100)),
                ('casa_central', models.CharField(max_length=100)),
                ('cantidad_estacionamiento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_dispo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=100)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Disponibilidad.sede')),
            ],
        ),
    ]
