# Generated by Django 3.1.3 on 2021-01-07 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disponibilidad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disponibilidad',
            name='reserva',
        ),
    ]
