# Generated by Django 3.1.3 on 2021-01-07 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0001_initial'),
        ('disponibilidad', '0002_remove_disponibilidad_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidad',
            name='reserva',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Reservas.reserva'),
        ),
    ]
