# Generated by Django 3.1.3 on 2021-01-04 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sede', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_reserva', models.CharField(max_length=30)),
                ('rut_reserva', models.CharField(max_length=200)),
                ('usuario_reserva', models.CharField(max_length=30)),
                ('patente', models.CharField(max_length=30)),
                ('fecha_entrada', models.DateTimeField()),
                ('fecha_salida', models.DateTimeField()),
                ('cantidad_horas', models.PositiveIntegerField()),
                ('motivo', models.CharField(max_length=1000)),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sede.sede')),
            ],
        ),
    ]
