# Generated by Django 3.1.3 on 2020-12-30 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_reserva', models.CharField(max_length=30)),
                ('rut_reserva', models.CharField(max_length=200)),
                ('usuario_reserva', models.CharField(max_length=30)),
                ('patente', models.CharField(max_length=30)),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('cantidad_horas', models.PositiveIntegerField()),
                ('sede', models.CharField(max_length=100)),
                ('motivo', models.CharField(max_length=1000)),
            ],
        ),
    ]
