# Generated by Django 3.1.3 on 2020-12-28 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_reserva', models.CharField(max_length=30)),
                ('Rut_reserva', models.CharField(max_length=200)),
                ('Usuario_Reserva', models.CharField(max_length=30)),
                ('Fecha_Reserva', models.DateField()),
                ('Cantidad_horas', models.PositiveIntegerField()),
                ('Patente', models.CharField(max_length=30)),
                ('Sede', models.CharField(choices=[('Casa central', 'Casa central'), ('Campus macul', 'Campus macul'), ('Campus providencia', 'Campus providencia')], default='Casa central', max_length=100)),
                ('Motivo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Reservamacul',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_reserva', models.CharField(max_length=30)),
                ('Rut_reserva', models.CharField(max_length=200)),
                ('Usuario_Reserva', models.CharField(max_length=30)),
                ('Fecha_Reserva', models.DateField()),
                ('Cantidad_horas', models.PositiveIntegerField()),
                ('Patente', models.CharField(max_length=30)),
                ('Sede', models.CharField(choices=[('Casa central', 'Casa central'), ('Campus macul', 'Campus macul'), ('Campus providencia', 'Campus providencia')], default='Campus macul', max_length=100)),
                ('Motivo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Reservaprovidencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_reserva', models.CharField(max_length=30)),
                ('Rut_reserva', models.CharField(max_length=200)),
                ('Usuario_Reserva', models.CharField(max_length=30)),
                ('Fecha_Reserva', models.DateField()),
                ('Cantidad_horas', models.PositiveIntegerField()),
                ('Patente', models.CharField(max_length=30)),
                ('Sede', models.CharField(choices=[('Casa central', 'Casa central'), ('Campus macul', 'Campus macul'), ('Campus providencia', 'Campus providencia')], default='Campus providencia', max_length=100)),
                ('Motivo', models.CharField(max_length=1000)),
            ],
        ),
    ]
